# Generated by Django 3.1.7 on 2021-06-06 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0002_commande'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=80)),
                ('numtel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.commande')),
            ],
        ),
    ]
