# Generated by Django 3.1.7 on 2021-06-06 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0003_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_tache', models.CharField(max_length=40)),
                ('dateHeure_debut', models.DateTimeField()),
                ('dateHeure_Fin', models.DateTimeField()),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.commande')),
            ],
        ),
    ]
