# Generated by Django 3.1.7 on 2021-06-06 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0004_tache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsablePrincipal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_prenomRp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rp', to=settings.AUTH_USER_MODEL)),
                ('tacheRp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tacherp', to='kms.tache')),
            ],
        ),
    ]
