# Generated by Django 3.1.7 on 2021-06-06 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0005_responsableprincipal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detecteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_Det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='det', to=settings.AUTH_USER_MODEL)),
                ('tacheDet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tachedet', to='kms.tache')),
            ],
        ),
    ]
