# Generated by Django 3.1.7 on 2021-06-06 15:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0006_detecteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribuer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_prenomC', models.ManyToManyField(related_name='contribuer', to=settings.AUTH_USER_MODEL)),
                ('tacheC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tachecon', to='kms.tache')),
            ],
        ),
    ]
