# Generated by Django 3.1.7 on 2021-06-06 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0007_contribuer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nom_prenomI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informer', to=settings.AUTH_USER_MODEL)),
                ('tacheI', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tacheinfo', to='kms.tache')),
            ],
        ),
    ]
