# Generated by Django 3.1.7 on 2021-06-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0008_informer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousCause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ishikawa', models.CharField(choices=[('depot', 'depot'), ('usine', 'usine'), ('matiére', 'matiére'), ('main d oeuvre', 'main d oeuvre'), ('machine embalage', 'machine embalage'), ('batteur', 'batteur'), ('methode', 'methode')], default='depot', max_length=200)),
                ('descriptionSousCause', models.CharField(max_length=200)),
            ],
        ),
    ]
