# Generated by Django 3.1.7 on 2021-06-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0009_souscause'),
    ]

    operations = [
        migrations.CreateModel(
            name='SousConsequance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionSousCons', models.CharField(max_length=200)),
            ],
        ),
    ]
