# Generated by Django 3.1.7 on 2021-06-06 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0010_sousconsequance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ishikawa', models.CharField(choices=[('depot', 'depot'), ('usine', 'usine'), ('matiére', 'matiére'), ('main d oeuvre', 'main d oeuvre'), ('machine embalage', 'machine embalage'), ('batteur', 'batteur'), ('methode', 'methode')], default='depot', max_length=200)),
                ('descriptionCause', models.CharField(max_length=200)),
                ('contribuerC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.contribuer')),
                ('sousCause', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.souscause')),
                ('sousConsequance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kms.sousconsequance')),
            ],
        ),
    ]
