# Generated by Django 3.1.7 on 2021-06-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0011_cause'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consequance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptionConsequance', models.CharField(max_length=200)),
            ],
        ),
    ]
