# Generated by Django 3.1.7 on 2021-06-06 16:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0012_consequance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateHeure_detection', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date créationRec')),
                ('sources', models.CharField(choices=[('client', 'client'), ('fournisseur', 'fournisseur'), ('interne', 'interne')], default='client', max_length=100)),
                ('nom_source', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Prix', 'Prix'), ('Qualité Produit', 'Qualité Produit'), ('Qualité Serice', 'Qualité Serice'), ('Modalité de Paiement', 'Modalité de Paiement'), ('Structure', 'Structure'), ('Délais', 'Délais')], default='Prix', max_length=100)),
                ('num_lots', models.IntegerField()),
                ('num_cmd', models.IntegerField()),
                ('quantite', models.CharField(max_length=60)),
                ('probabiliter', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=100)),
                ('graviter', models.CharField(choices=[('pas grave', 'pas grave'), ('moyen', 'moyen'), ('grave', 'grave'), ('trés grave', 'trés grave')], default='moyen', max_length=100)),
                ('status', models.CharField(choices=[('en cours', 'en cours'), (' en attente', ' en attente'), ('clôturer ', 'clôturer ')], default='en cours', max_length=100)),
                ('cause_rec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.cause')),
                ('consequence_rec', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.consequance')),
                ('contribuer', models.ManyToManyField(to='kms.Contribuer')),
                ('detecteurs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.detecteur')),
                ('informer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.informer')),
                ('responsable_principale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.responsableprincipal')),
            ],
        ),
    ]
