# Generated by Django 3.1.7 on 2021-06-06 16:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0013_reclamations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detector', models.CharField(max_length=40)),
                ('dateHeure_detection', models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Date création')),
                ('sources', models.CharField(choices=[('client', 'client'), ('fournisseur', 'fournisseur'), ('interne', 'interne')], default='interne', max_length=100)),
                ('nom_source', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=100)),
                ('ishikawa', models.CharField(choices=[('depot', 'depot'), ('usine', 'usine'), ('matiére', 'matiére'), ('main d oeuvre', 'main d oeuvre'), ('machine embalage', 'machine embalage'), ('batteur', 'batteur'), ('methode', 'methode')], default='methode', max_length=100)),
                ('probabiliter', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=100)),
                ('graviter', models.CharField(choices=[('pas grave', 'pas grave'), ('moyen', 'moyen'), ('grave', 'grave'), ('trés grave', 'trés grave')], default='grave', max_length=100)),
                ('status', models.CharField(choices=[('en cours', 'en cours'), (' en attente', ' en attente'), ('clôturer ', 'clôturer ')], default='en attente', max_length=100)),
                ('responsable_principale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.responsableprincipal')),
            ],
        ),
    ]
