# Generated by Django 3.1.7 on 2021-06-10 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0015_reclamations_detector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='contribuerC',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.contribuer'),
        ),
    ]
