# Generated by Django 3.1.7 on 2021-06-10 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0016_auto_20210610_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cause',
            name='sousCause',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.souscause'),
        ),
        migrations.AlterField(
            model_name='cause',
            name='sousConsequance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.sousconsequance'),
        ),
    ]
