# Generated by Django 3.1.7 on 2021-06-11 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kms', '0023_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reclamations',
            name='statu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.status'),
        ),
        migrations.AddField(
            model_name='reclamations',
            name='types',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='kms.types'),
        ),
    ]
